#!/usr/bin/env bash
#Install load balancer
# installs a nginx with redirection
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
echo "frontend web_front
bind *:80
mode http
default_backend web_back
backend web_back
balance roundrobin
server web1 35.227.78.73 check
server web2 34.75.67.238 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
