#!/usr/bin/env bash
#Install load balancer
# installs a nginx with redirection
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
echo "frontend web_front
bind *:80
mode http
default_backend web_back
backend web_back
balance roundrobin
server web1 54.89.119.136 check
server web2 34.204.95.144 check
["web-01", "web-02"]
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
